import axios, { Axios, AxiosInstance } from 'axios';
import { fabric } from 'fabric';
import { Vector2 } from 'three';
import { CSS3DObject } from 'three/examples/jsm/renderers/CSS3DRenderer';
import { create } from 'apisauce';

export class Face extends CSS3DObject {
  public fabricCanvas: fabric.Canvas | null = null;
  public ticketSize: Vector2 | null = null;
  public side: 'front' | 'back' | null = null;
  public decoration: string | null = null;
  public axiosInstance: AxiosInstance | null = null;
  constructor(
    ticketSize: Vector2, // (width, height)
    side: 'front' | 'back',
    decoration: string
  ) {
    super(document.createElement('div'));
    this.ticketSize = ticketSize;
    this.side = side;
    this.decoration = decoration;
    this.initAxios();
    this.initCanvas();
    this.getDecoration();
  }

  public async initAxios() {
    // define the api
    const api = create({
      baseURL: 'http://192.168.0.59:8080',
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': 'http://localhost:3000',
      },
      withCredentials: true,
    });
    //api.setHeader(
    //  'Cookie',
    //  'access=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibmF2ZXIgbHphV19oUmprc1kzZXo1NUtJckpXdE9mMk1qTi1GZzJJbUF5SXBPOFNlcyIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTQzODYzMTcsImV4cCI6MTcxNDM4NjkxN30.PxsZSQ2ylzs9w_8rpKz5wEG7PrxeNB7pF8anrWM0BDo'
    //);
    // start making calls
    api
      .post('/api/tickets/1212312313')
      .then((response) => console.log(response));
  }

  public initCanvas(): void {
    this.fabricCanvas = new fabric.Canvas(this.name, {
      width: this.ticketSize!.x,
      height: this.ticketSize!.y,
    });
    this.element = this.fabricCanvas.getElement();
  }

  public addRect(): void {
    const rect = new fabric.Rect({
      left: 0,
      top: 0,
      fill: '#FF0000',
      width: 700,
      height: 600,
    });
    this.fabricCanvas!.add(rect);
  }

  public addText(): void {
    const text = new fabric.Text('ll', {
      left: 20,
      top: 5,
      fill: '#FFFFFF',
      fontSize: 8,
      fontFamily: 'Arial',
    });
    this.fabricCanvas!.add(text);
  }

  public addImage(): void {
    const imgElement = document.createElement('img');
    imgElement.src = 'assets/heart.png';
    const image = new fabric.Image(imgElement, {
      left: 0,
      top: 0,
      angle: 0,
      width: 100,
      height: 90,
    });
    this.fabricCanvas!.add(image);
  }

  public getDecoration(): void {
    this.fabricCanvas!.loadFromJSON(
      {
        version: '5.3.0',
        objects: [
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 45,
            top: 25,
            width: 93.32,
            height: 97.63,
            fill: '#FFFFFF',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: 'hello\nworld',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'left',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'image',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 122,
            top: 251,
            width: 100,
            height: 75,
            fill: 'rgb(0,0,0)',
            stroke: null,
            strokeWidth: 0,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            cropX: 0,
            cropY: 0,
            src: 'http://localhost:3000/assets/heart.png',
            crossOrigin: null,
            filters: [],
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 45,
            top: 25,
            width: 93.32,
            height: 97.63,
            fill: '#FFFFFF',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: 'hello\nworld',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'left',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 74,
            top: 412,
            width: 212.96,
            height: 97.63,
            fill: '#006BFF',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: '안녕하세요!!!\n안녕!',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'center',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 74,
            top: 412,
            width: 212.96,
            height: 97.63,
            fill: '#006BFF',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: '안녕하세요!!!\n안녕!',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'center',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 74,
            top: 412,
            width: 212.96,
            height: 97.63,
            fill: '#006BFF',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: '안녕하세요!!!\n안녕!',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'center',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 146.5,
            top: 291.55,
            width: 155.59,
            height: 45.2,
            fill: '#FF0000',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 271.98,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: 'SSALON',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'left',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
          {
            type: 'i-text',
            version: '5.3.0',
            originX: 'left',
            originY: 'top',
            left: 146.5,
            top: 291.55,
            width: 155.59,
            height: 45.2,
            fill: '#FF0000',
            stroke: null,
            strokeWidth: 1,
            strokeDashArray: null,
            strokeLineCap: 'butt',
            strokeDashOffset: 0,
            strokeLineJoin: 'miter',
            strokeUniform: false,
            strokeMiterLimit: 4,
            scaleX: 1,
            scaleY: 1,
            angle: 271.98,
            flipX: false,
            flipY: false,
            opacity: 1,
            shadow: null,
            visible: true,
            backgroundColor: '',
            fillRule: 'nonzero',
            paintFirst: 'fill',
            globalCompositeOperation: 'source-over',
            skewX: 0,
            skewY: 0,
            fontFamily: 'Times New Roman',
            fontWeight: 'normal',
            fontSize: 40,
            text: 'SSALON',
            underline: false,
            overline: false,
            linethrough: false,
            textAlign: 'left',
            fontStyle: 'normal',
            lineHeight: 1.16,
            textBackgroundColor: '',
            charSpacing: 0,
            styles: [],
            direction: 'ltr',
            path: null,
            pathStartOffset: 0,
            pathSide: 'left',
            pathAlign: 'baseline',
          },
        ],
      },
      (e: any) => {
        console.log(e);
        this.fabricCanvas!.renderAll();
      }
    );
  }
}
